name: Messari .NET Client - Build

on: 
  push:
    branches-ignore:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src